# Generated by Django 4.2.27 on 2026-01-07 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_types', models.JSONField(default=list)),
                ('certification_level', models.CharField(blank=True, max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('OFFLINE', 'Offline'), ('AVAILABLE', 'Available'), ('ON_DUTY', 'On Duty'), ('IN_EMERGENCY', 'In Emergency'), ('BREAK', 'On Break')], default='OFFLINE', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('current_emergency_id', models.UUIDField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('vehicle_capacity', models.IntegerField(default=1)),
                ('total_emergencies', models.IntegerField(default=0)),
                ('completed_emergencies', models.IntegerField(default=0)),
                ('avg_response_time', models.DurationField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rating_count', models.IntegerField(default=0)),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('max_distance', models.IntegerField(default=50000)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'providers',
            },
        ),
    ]
