# Generated by Django 4.2.27 on 2026-01-07 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_profile",
                to="users.user",
            ),
        ),
    ]
